<a href="https://colab.research.google.com/github/M-MubashirAI/Data-Science-practice/blob/main/Numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **NumPy**

NumPy is a short form of Numericle Python.
In 2005 Travis Oliphant created NumPy Package.NumPy is package that defines multi-dimensional array object and associate fast math functions that operate.
It has working domain in linear Algebra, Fourier Transformation and Matrics. In simple it is the fundamental package scientific computing in python.

# **Array**
1.Array is defined as a colledtion of items that are stored at contiguous memory locations.
2. It is a container which can hold a fixed number of items, and these items shluld be of the same type.
3. A combination of arrays saves a lot of time. THe array can reduce the overall size fo the code.

# **Advantages of Using Arrays:**
1. NumPy uses much less memory to store data.
2. NumPy makes it extremely easy fo perform mathemtical operations on it.

3. Used for the creation of N-dimensional arrays.
4.Finding elements in NumPy array is easy.

# **Arrays difference b/w Lists:**
1. A List cannot directly handle Mathematical perations, while Array can.
2. An arry consumes less memory than a List.
3. Using an Array is fster thatn List.
4. A List can store different datatypes, while you can't do that in an Arry.
5. A List is easier to mofify since a list store each element individually, it is easier to add and delete an element than an aray does.
6. In Lists one can have nested data with different size, while you cannot do the same in array.






In [ ]:
!pip install NumPy

In [ ]:
import numpy as np

a = np.array([20,30,40])
b = np.array([10,50,70])
print(a)
print(b)
print(a+b)
print(a*b)
print(a-b)

[20 30 40]
[10 50 70]
[ 30  80 110]
[ 200 1500 2800]
[ 10 -20 -30]


In [ ]:
x = np.array([20,50])
y =np.array([40])
print(x*y)
print(x+y)

[ 800 2000]
[60 90]


In [ ]:
a = np.array([20,40,"60"])
print(a)

['20' '40' '60']


In [ ]:
l1 = [20,30,40]
l2 = [10,50,70]
print(l1 + l2)
# But here not doing add and doing concatenate.

[20, 30, 40, 10, 50, 70]


# **NumPy-creating Arrays,Slicing and Attributes**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a =np.array([20,40,60])
print(a[2:])
print(a[:3])
print(a[1:2])
print(a[:1])

[60]
[20 40 60]
[40]
[20]


In [ ]:
arr = np.array([[23,56,80,70,90],[20,30,50,40,50]])
# here 1 show 2nd index row array is doing be slicing
print(arr[1,0:3])
# here 0 show 1rst index row array is doing be slicing
print(arr[0,1:])
# Now we Know about the attributes
print(np.shape(arr))
print(np.size(arr))
# dimension tell us that two dimension one is row and second is colunm, that makes 2
print(np.ndim(arr))
print(arr.dtype)

[20 30 50]
[56 80 70 90]
(2, 5)
10
2
int64


In [ ]:
import numpy as np
a = np.array([[10,20,50,30,40],[60,70,80,90,10]])
print(a[0,1:2])
print(a[1,2:])
print(a.shape)
print(a.size)
print(a.dtype)
print(type(a))

[20]
[80 90 10]
(2, 5)
10
int64
<class 'numpy.ndarray'>


# **Insepcting an Arrays**
1. a.shape---Array dimensions and number of rows and columns.
2. len(a)___ Lengthe fo array.
3. b.ndim___ Numberof array dimensions.
4. e.size___ Number of array elements.
5. b.dtype___ Data type of array elements.
6. astype(int)___ Convert on array to a different type.

In [ ]:
a = [30,50,20,60]
arr = np.array(a)
print(arr)
print(arr.shape) # rows,columns
print(len(arr)) # number of nested values
print(arr.ndim) # number of array dimension
print(type(arr)) # dtypes of variables
print(arr.dtype)# dtypes of values
print(arr.size) # number of elements
print(arr.astype(float))

[30 50 20 60]
(4,)
4
1
<class 'numpy.ndarray'>
int64
4
[30. 50. 20. 60.]


# **Mathematical Operations and Functions on Arrays**


*   g = a-b
*np.subtract(a,b)
*b + an
*   p.add (b,a)
*a/b
*np.divide (a,b)
*a*b
*np.multiply(a,b)
*np.exp(b)
*np.sqrt(b)
*np.pow(a)


In [ ]:
# Addition
sas = np.array([[20,30],[40,50]])
sas1= np.array([[10,50],[20,50]])
print(sas+sas1)
print(np.add(sas,sas1))
print(np.add(sas,sas1))

[[ 30  80]
 [ 60 100]]
[[ 30  80]
 [ 60 100]]
[[ 30  80]
 [ 60 100]]


In [ ]:
# subtraction
sas = np.array([[20,30],[40,50]])
sas1= np.array([[10,50],[20,50]])
print(sas-sas1)
print(np.subtract(sas,sas1))

[[ 10 -20]
 [ 20   0]]
[[ 10 -20]
 [ 20   0]]


In [ ]:
# Multiplication
print(sas*sas1)
print(np.multiply(sas,sas1))

[[ 200 1500]
 [ 800 2500]]
[[ 200 1500]
 [ 800 2500]]


In [ ]:
# Divsion
print(sas/sas1)
print(np.divide(sas,sas1))

[[2.  0.6]
 [2.  1. ]]
[[2.  0.6]
 [2.  1. ]]


In [ ]:
a = [2,3,4,5,6]
b = [2]
print(np.power(a,b))

[ 4  9 16 25 36]


In [ ]:
c = [4,9,16,25,36]
print(np.sqrt(c))

[2. 3. 4. 5. 6.]


In [ ]:
a = np.array([[23,43,53,66],[32,65,87,56]])
b = np.array([[34,88,99,86],[56,45,98,56]])
print(a+b)
print(np.add(a,b))

[[ 57 131 152 152]
 [ 88 110 185 112]]
[[ 57 131 152 152]
 [ 88 110 185 112]]


In [ ]:
a = [2,3,4,5,6,7]
b = [2]
print(np.power(a,b))

[ 4  9 16 25 36 49]


In [ ]:
v=[4,9,16,25,36,49]
print(np.sqrt(v))

[2. 3. 4. 5. 6. 7.]


# **Combining and Spliting Arrays**

In [ ]:
a = [20,30,50]
b = [2,3.5]
print(a+b)

[20, 30, 50, 2, 3.5]


In [ ]:
a = np.array([20,30,50])
b = np.array([2,3,5])
print(np.concatenate([a,b],axis = 0))

[20 30 50  2  3  5]


In [ ]:
a = np.array([[20,30],[40,60]])
b = np.array([[4,4],[5,3]])
print(np.concatenate([a,b],axis = 1))

[[20 30  4  4]
 [40 60  5  3]]


In [ ]:
a = np.array([[20,30],[40,60]])
b = np.array([[4,4],[5,3]])
print(np.concatenate([a,b],axis = 0))

[[20 30]
 [40 60]
 [ 4  4]
 [ 5  3]]


In [ ]:
print(np.hstack([a,b])) # Horizontal concatenation

[[20 30  4  4]
 [40 60  5  3]]


In [ ]:
print(np.hstack([a,b]))

[[20 30  4  4]
 [40 60  5  3]]


In [ ]:
print(np.vstack([a,b])) # Vertical concatenation

[[20 30]
 [40 60]
 [ 4  4]
 [ 5  3]]


In [ ]:
print(np.vstack([a,b]))

[[20 30]
 [40 60]
 [ 4  4]
 [ 5  3]]


In [ ]:
a = ([20,30,40,60,70,80,90])
print(np.array_split(a,3))

[array([20, 30, 40]), array([60, 70]), array([80, 90])]


In [ ]:
a = ([20,30,40,50,60,70,80,90])
b = np.array_split(a,3)
print(b[1])

[50 60 70]


# **Adding and removing the elements in the Arrays**


*   np.append(h,g)_Appned items to an array
*   np.insert(a,1,5) _Inserts itens in an aray
*np.delete(a,[1])__Delete items from an array



In [ ]:
a = np.array([20,30,40])
print(np.append(a,50))
print(np.insert(a,1,10)) # Array,index and value

[20 30 40 50]
[20 10 30 40]


In [ ]:
n= np.array([20,50,30,10])
print(np.append(n,70))

[20 50 30 10 70]


In [ ]:
print(np.delete(n,3))

[20 50 30]


In [ ]:
print(np.delete(a,0))

[30 40]


# **NumPy__ Sort,Filter and Search**

In [ ]:
# Sort Function
c = ([70,30,80,60])
print(np.sort(c))

[30 60 70 80]


In [ ]:
d = ([[20,70,30,50],[40,20,10,70]])
print(np.sort(d))

[[20 30 50 70]
 [10 20 40 70]]


In [ ]:

arr = ([20,60,10,40])
z = np.where(arr == 60)
print(z)

(array([], dtype=int64),)


<ipython-input-57-a86902b9893e>:2: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  z = np.where(arr == 60)


In [ ]:
# Search function
k = ([10,20,30,50])
ss = np.searchsorted(k,50)
print(ss)

3


In [ ]:
# Filter Function
k = np.array([20,30,10,50])
arr = [True,False,True,False]
new = k[arr]
print(new)

[20 10]


In [ ]:
A = ([20,50,60,70])
B = A>55
new = A[B]
print(new)

TypeError: '>' not supported between instances of 'list' and 'int'

# **Aggregating Functions in python**

In [ ]:
a = ([20,50,30,80])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

180
20
80
4
45.0
[ 20  70 100 180]
[     20    1000   30000 2400000]


# **Statistical Functions in Arrays**

In [ ]:
import numpy
import statistics as sts555

In [ ]:
a = [100,150,130,100,200,180,160]
new = np.array(a)
print(np.mean(new)) # The sum of value\ the count of the element
print(np.median(new)) # middle value after sorting value
print(sts.mode(new)) # more occurance value
print(np.std(new)) # Show the spreading value
print(np.var(new))

145.71428571428572
150.0
100
35.39860483818248
1253.0612244897961


In [ ]:
# Correlation
# -1 represents the inversely proportional to relationship
#  1 represents the proportiona relationship
#  0 represents no relationship
Tobacco_cunsumption = [20,50,40,100,70,90]
deaths = [120,140,111,60,110,104]
print(np.corrcoef(Tobacco_cunsumption,deaths))

[[ 1.         -0.71016181]
 [-0.71016181  1.        ]]


# **Introduction to Pandas**


*   Pandas is a Python package providing fasr, flexible, and expressive data structures designed to make working with "relational" or "labeled" data both easy and intuitive
*   Here are just a few of the things that pandas does well:
It has functions for analyzing, cleaning, exploring, and manipulating data.
*The name "Pandas" has a reference to both "Panel Data", and "Python data Analysis" and was created by Wes McKinney in 2008.



# **Pandas Applications**


*   Easy handling of missing data.
*Size mutability : columns can be inserted and deleted from DataFrame and higher dimensional objects
*   Automatic and explicit data alignment: objects can be explicitly aligned to a set of Labels,or the user can simply ignore the labels and let Series, DataFrame etc.
*Automatically align the data for you in computations.
* Powerful, flexble group by functionality.
* Intelligent label-based slicing, fancy icdexing,and subsetting of large data sets.
*Intuitive merging and joining data sets.
*Flexible reshaping and pivoting of data sets.

# **Data Structures in**
THe best way to think about the pandas data structures is as flexible containers for lower dimensionsl data. For example, DataFrame is a container for Series, and Series is a container for scalars. We would like to be able to insert and remover objects from these containers in a dictionary-like fashion.


# **Series in Pandas:**
Pandas Series is a one-dimensional labeled array (column) capable of holding data of any type (integer, string, float, python objects, etc.). The axis labels are collectively called index. Pandas Series is nothing but a column in an excel sheet.

The object supports both integer and label-based indexing and provides a host of methods for performing operations involving the index.


# **DataFrames:**
Pandas DataFrame is two-dimensional size-mutable, potentially hererogeneous tabluar dat structure with labeled axes (rows and columns). A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns. Pandas DaraFrame consists of three principal components, the data, rows, and columns.




# **Creation of DataFrame in pandas**

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd


In [ ]:
company = {"Name":["jhon","maki","lisa"],
           "Age":[20,40,38],
           "Salary":[1000,2800,5000]}
df = pd.DataFrame(company)
print(df)


   Name  Age  Salary
0  jhon   20    1000
1  maki   40    2800
2  lisa   38    5000


In [ ]:
data= {"Students":["Kareem","Tufail","Madni","Saif"],
       "Age":[20,23,19,21],
       "Number":[30,80,90,100]}
df= pd.DataFrame(data)
print(df)

  Students  Age  Number
0   Kareem   20      30
1   Tufail   23      80
2    Madni   19      90
3     Saif   21     100


In [ ]:
data = pd.read_csv("/content/titanic_cleaned.csv")
print(data)

FileNotFoundError: [Errno 2] No such file or directory: '/content/titanic_cleaned.csv'

In [ ]:
!pip install openpyxl

In [ ]:
import pandas as pd

data = pd.read_excel("/content/ESD.xlsx")
print(data)

       EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT   
1    E04105    Theodore Dinh       Technical Architect          IT   
2    E02572     Luna Sanders                  Director     Finance   
3    E02832  Penelope Jordan  Computer Systems Manager          IT   
4    E01639        Austin Vo               Sr. Analyst     Finance   
..      ...              ...                       ...         ...   
995  E03094     Wesley Young               Sr. Analyst   Marketing   
996  E01909     Lillian Khan                   Analyst     Finance   
997  E04398      Oliver Yang                  Director   Marketing   
998  E02521      Lily Nguyen               Sr. Analyst     Finance   
999  E03545      Sofia Cheng            Vice President  Accounting   

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604 

In [ ]:
print(data.head(5))

     EEID        Full Name                 Job Title Department  \
0  E02387      Emily Davis                Sr. Manger         IT   
1  E04105    Theodore Dinh       Technical Architect         IT   
2  E02572     Luna Sanders                  Director    Finance   
3  E02832  Penelope Jordan  Computer Systems Manager         IT   
4  E01639        Austin Vo               Sr. Analyst    Finance   

            Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0  Research & Development  Female      Black   55 2016-04-08         141604   
1           Manufacturing    Male      Asian   59 1997-11-29          99975   
2     Speciality Products  Female  Caucasian   50 2006-10-26         163099   
3           Manufacturing  Female  Caucasian   26 2019-09-27          84913   
4           Manufacturing    Male      Asian   55 1995-11-20          95409   

   Bonus %        Country       City  Exit Date  
0     0.15  United States    Seattle 2021-10-16  
1     0.00          Ch

In [ ]:
print(data.tail(5))

       EEID     Full Name       Job Title  Department        Business Unit  \
995  E03094  Wesley Young     Sr. Analyst   Marketing  Speciality Products   
996  E01909  Lillian Khan         Analyst     Finance  Speciality Products   
997  E04398   Oliver Yang        Director   Marketing  Speciality Products   
998  E02521   Lily Nguyen     Sr. Analyst     Finance  Speciality Products   
999  E03545   Sofia Cheng  Vice President  Accounting            Corporate   

     Gender  Ethnicity  Age  Hire Date  Annual Salary  Bonus %        Country  \
995    Male  Caucasian   33 2016-09-18          98427     0.00  United States   
996  Female      Asian   44 2010-05-31          47387     0.00          China   
997    Male      Asian   31 2019-06-10         176710     0.15  United States   
998  Female      Asian   33 2012-01-28          95960     0.00          China   
999  Female      Asian   63 2020-07-26         216195     0.31  United States   

         City  Exit Date  
995  Columbus    

In [ ]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   EEID           1000 non-null   object        
 1   Full Name      1000 non-null   object        
 2   Job Title      1000 non-null   object        
 3   Department     1000 non-null   object        
 4   Business Unit  1000 non-null   object        
 5   Gender         1000 non-null   object        
 6   Ethnicity      1000 non-null   object        
 7   Age            1000 non-null   int64         
 8   Hire Date      1000 non-null   datetime64[ns]
 9   Annual Salary  1000 non-null   int64         
 10  Bonus %        1000 non-null   float64       
 11  Country        1000 non-null   object        
 12  City           1000 non-null   object        
 13  Exit Date      85 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2), object(9)
memory usage: 109.5

In [ ]:
print(data.describe())

               Age  Annual Salary      Bonus %
count  1000.000000    1000.000000  1000.000000
mean     44.382000  113217.365000     0.088660
std      11.246981   53545.985644     0.117856
min      25.000000   40063.000000     0.000000
25%      35.000000   71430.250000     0.000000
50%      45.000000   96557.000000     0.000000
75%      54.000000  150782.250000     0.150000
max      65.000000  258498.000000     0.400000


In [ ]:
print(data.isnull())

      EEID  Full Name  Job Title  Department  Business Unit  Gender  \
0    False      False      False       False          False   False   
1    False      False      False       False          False   False   
2    False      False      False       False          False   False   
3    False      False      False       False          False   False   
4    False      False      False       False          False   False   
..     ...        ...        ...         ...            ...     ...   
995  False      False      False       False          False   False   
996  False      False      False       False          False   False   
997  False      False      False       False          False   False   
998  False      False      False       False          False   False   
999  False      False      False       False          False   False   

     Ethnicity    Age  Hire Date  Annual Salary  Bonus %  Country   City  \
0        False  False      False          False    False    False  Fals

In [ ]:
print(data.isnull().sum())

EEID               0
Full Name          0
Job Title          0
Department         0
Business Unit      0
Gender             0
Ethnicity          0
Age                0
Hire Date          0
Annual Salary      0
Bonus %            0
Country            0
City               0
Exit Date        915
dtype: int64


# **Handling Duplicate Values in Pandas**

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv("/content/company1.csv")

In [ ]:
print(df)

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0


In [ ]:
print(df.duplicated("EEID").sum())

2


In [ ]:
print(df.drop_duplicates(

))

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN


In [ ]:
print(df.drop_duplicates("EEID"))

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN


# **Working with missing Data in pandas**

In [ ]:
print(df)

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0


In [ ]:
print(df.isnull().sum())

EEID      0
Name      1
gender    1
salary    2
dtype: int64


In [ ]:
print(df.dropna())

    EEID    Name gender   salary
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0


In [ ]:
import numpy as np
print(df)

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0


In [ ]:
print(df.replace(np.nan, 30000))

    EEID      Name gender   salary
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali  30000  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     30000      M  25000.0
5  EMP06     rohit      M  30000.0
6  EMP02     rohit      M  25000.0


In [ ]:
df["salary"] = df["salary"].replace(np.nan, 26000)
print(df)

    EEID      Name gender   salary
0  EMP01    ayushi      F  26000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  26000.0
6  EMP02     rohit      M  25000.0


In [ ]:
print(df["salary"].mean())

24857.14285714286


In [ ]:
df["salary"] = df["salary"].replace(np.nan,26000)
print(df)

    EEID      Name gender   salary
0  EMP01    ayushi      F  26000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  26000.0
6  EMP02     rohit      M  25000.0


In [ ]:
df = pd.read_csv("/content/company1.csv")
print(df)

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0


In [ ]:
print(df.drop_duplicates("EEID"))

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN


In [ ]:
print(df["salary"].mean())

24400.0


In [ ]:
print(df.isnull().sum())

EEID      0
Name      1
gender    1
salary    2
dtype: int64


In [ ]:
df["salary"] = df["salary"].replace(np.NaN,24400)
print(df)

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0


In [ ]:
import pandas as pd
import numpy as np


In [ ]:
print(df)

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0


In [ ]:
print(df.fillna(method = "bfill"))

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      F  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     rohit      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0


In [ ]:
print(df.fillna(method = "ffill"))

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      M  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05    ayushi      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0


In [ ]:
print(df.fillna("hi"))

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali     hi  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05        hi      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0


# **Columns Transformation Pandas part 01**

In [ ]:
import pandas as pd
df = pd.read_excel("/content/ESD.xlsx")

In [ ]:

df.loc[(df["Bonus %"] == 0), "GetsBonus"] = "no bonus"
df.loc[(df["Bonus %"] > 0, "GetsBonus")] = "bonus"
print(df.head(10))

     EEID        Full Name                 Job Title  Department  \
0  E02387      Emily Davis                Sr. Manger          IT   
1  E04105    Theodore Dinh       Technical Architect          IT   
2  E02572     Luna Sanders                  Director     Finance   
3  E02832  Penelope Jordan  Computer Systems Manager          IT   
4  E01639        Austin Vo               Sr. Analyst     Finance   
5  E00644     Joshua Gupta    Account Representative       Sales   
6  E01550      Ruby Barnes                   Manager          IT   
7  E04332      Luke Martin                   Analyst     Finance   
8  E04533    Easton Bailey                   Manager  Accounting   
9  E03838  Madeline Walker               Sr. Analyst     Finance   

            Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0  Research & Development  Female      Black   55 2016-04-08         141604   
1           Manufacturing    Male      Asian   59 1997-11-29          99975   
2     Speciali

# **columns Transformation pandas part 02**

In [ ]:
data = {"Months":["january","march","april","may"]}
df = pd.DataFrame(data)
print(df)

    Months
0  january
1    march
2    april
3      may


In [ ]:
def extract(value):
  return value[0:3]

df["short_months"] = df["Months"].map(extract)
print(df)

    Months short_months
0  january          jan
1    march          mar
2    april          apr
3      may          may


# **Group By in Pandas**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/ESD.xlsx")
print(df)

       EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT   
1    E04105    Theodore Dinh       Technical Architect          IT   
2    E02572     Luna Sanders                  Director     Finance   
3    E02832  Penelope Jordan  Computer Systems Manager          IT   
4    E01639        Austin Vo               Sr. Analyst     Finance   
..      ...              ...                       ...         ...   
995  E03094     Wesley Young               Sr. Analyst   Marketing   
996  E01909     Lillian Khan                   Analyst     Finance   
997  E04398      Oliver Yang                  Director   Marketing   
998  E02521      Lily Nguyen               Sr. Analyst     Finance   
999  E03545      Sofia Cheng            Vice President  Accounting   

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604 

In [ ]:
gp = df.groupby('Department').agg({"Gender":"count"})
print(gp)

                 Gender
Department             
Accounting           96
Engineering         158
Finance             120
Human Resources     125
IT                  241
Marketing           120
Sales               140


In [ ]:
gp = df.groupby("Job Title").agg({"Gender":"count"})
print(gp)

                                Gender
Job Title                             
Account Representative              21
Analyst                             51
Analyst II                          53
Automation Engineer                  7
Business Partner                    19
Cloud Infrastructure Architect      15
Computer Systems Manager            21
Controls Engineer                   15
Development Engineer                19
Director                           121
Engineering Manager                 20
Enterprise Architect                18
Field Engineer                      21
HRIS Analyst                        16
IT Coordinator                      11
IT Systems Architect                12
Manager                             98
Network Administrator               10
Network Architect                   18
Network Engineer                     7
Operations Engineer                 12
Quality Engineer                    20
Service Desk Analyst                10
Solutions Architect      

In [ ]:
gp = df.groupby(["Department","Gender"]).agg({"EEID":"count"})
print(gp)

                        EEID
Department      Gender      
Accounting      Female    53
                Male      43
Engineering     Female    80
                Male      78
Finance         Female    69
                Male      51
Human Resources Female    64
                Male      61
IT              Female   119
                Male     122
Marketing       Female    57
                Male      63
Sales           Female    76
                Male      64


In [ ]:
gp1 = df.groupby("Country").agg({"Age":"mean"})
print(gp1)

                     Age
Country                 
Brazil         43.654676
China          45.389908
United States  44.197512


In [ ]:
gp1 = df.groupby(["Country","Gender"]).agg({"Annual Salary":"max","Age":"min"})
print(gp1)


                      Annual Salary  Age
Country       Gender                    
Brazil        Female         258426   25
              Male           249506   26
China         Female         249686   25
              Male           257194   25
United States Female         258498   25
              Male           258081   25


In [ ]:
gp2 = df.groupby("Country").agg({"Annual Salary":"mean"})
print(gp2)

               Annual Salary
Country                     
Brazil         112324.834532
China          113823.532110
United States  113204.794712


# **Merge, Join and Concatenate in Pandas**

In [ ]:
import pandas as pd
df1 = {"EEId":["E01","E02","E03","E04","E05","E06"],
       "Name":["john","kiki","maki","karam","nasaka","mali"],
       "Age":[22,55,33,77,60,44]}
df2 = {"EEID":["E01","E02","E03","E04","E05","E06"],
       "salary":[28000,30000,54000,60000,70000,80000]}

data = pd.DataFrame(df1)
data2 = pd.DataFrame(df2)
print(data)
print(data2)

  EEId    Name  Age
0  E01    john   22
1  E02    kiki   55
2  E03    maki   33
3  E04   karam   77
4  E05  nasaka   60
5  E06    mali   44
  EEID  salary
0  E01   28000
1  E02   30000
2  E03   54000
3  E04   60000
4  E05   70000
5  E06   80000


In [ ]:
df1 = {"EEID":["E01","E02","E03","E04","E05","E06"],
       "Name":["john","kiki","maki","karam","nasaka","mali"],
       "Age":[22,55,33,77,60,44]}
df2 = {"EEID":["E01","E02","E03","E04","E05","E06"],
       "salary":[28000,30000,54000,60000,70000,80000]}

data = pd.DataFrame(df1)
data2 = pd.DataFrame(df2)


merged_df = pd.merge(data,data2, on="EEID")
print(merged_df)

  EEID    Name  Age  salary
0  E01    john   22   28000
1  E02    kiki   55   30000
2  E03    maki   33   54000
3  E04   karam   77   60000
4  E05  nasaka   60   70000
5  E06    mali   44   80000


In [ ]:
print(df.join([data,data2]))

ValueError: Indexes have overlapping values: Index(['EEID', 'Age'], dtype='object')

In [ ]:
df1 = {"EEID":["E01","E02","E03","E04","E05","E06"],
       "Name":["john","kiki","maki","karam","nasaka","mali"],
       "Age":[22,55,33,77,60,44]}

df2 = {"EEID":["E07","E08","E09","E010","E011","E012"],
       "salary":[28000,30000,54000,60000,70000,80000]}
df3 = pd.DataFrame(df1)
df4 = pd.DataFrame(df2)
print(pd.concat([df3,df4]))

   EEID    Name   Age   salary
0   E01    john  22.0      NaN
1   E02    kiki  55.0      NaN
2   E03    maki  33.0      NaN
3   E04   karam  77.0      NaN
4   E05  nasaka  60.0      NaN
5   E06    mali  44.0      NaN
0   E07     NaN   NaN  28000.0
1   E08     NaN   NaN  30000.0
2   E09     NaN   NaN  54000.0
3  E010     NaN   NaN  60000.0
4  E011     NaN   NaN  70000.0
5  E012     NaN   NaN  80000.0


# **Pandas | compare DataFrame**

In [ ]:
dic = {"Fruits":["mango","apple","banana","papaya"],
       "price":[100,200,150,15],
       "quantity":[12,10,10,15]}

df = pd.DataFrame(dic)
print(df)
df2 = df.copy()

df2.loc[0,"price"] = 150
df2.loc[1,"price"] = 300
df2.loc[2,"price"] =200
df2.loc[3,"price"] =30
df2.loc[0,"quantity"] = 6
df2.loc[1,"quantity"] = 5
df2.loc[2,"quantity"] = 9
df2.loc[3,"quantity"] = 8
print(df2)
print(df.compare(df2))
print(df.compare(df2,keep_equal = True))
print(df.compare(df2,keep_shape = False))

   Fruits  price  quantity
0   mango    100        12
1   apple    200        10
2  banana    150        10
3  papaya     15        15
   Fruits  price  quantity
0   mango    150         6
1   apple    300         5
2  banana    200         9
3  papaya     30         8
  price       quantity      
   self other     self other
0   100   150       12     6
1   200   300       10     5
2   150   200       10     9
3    15    30       15     8
  price       quantity      
   self other     self other
0   100   150       12     6
1   200   300       10     5
2   150   200       10     9
3    15    30       15     8
  price       quantity      
   self other     self other
0   100   150       12     6
1   200   300       10     5
2   150   200       10     9
3    15    30       15     8


# Pandas --pivoting and Melting **DataFrame**

In [ ]:
dic = {"keys":["k1","k2","k3","k4"],
       "names":["john","petter","lisa","tika"],
       "house":["blue","green","yellow","red"]}

df = pd.DataFrame(dic)
print(df)
print(df.pivot("keys","names","house"))

  keys   names   house
0   k1    john    blue
1   k2  petter   green
2   k3    lisa  yellow
3   k4    tika     red
names  john    lisa petter tika
keys                           
k1     blue     NaN    NaN  NaN
k2      NaN     NaN  green  NaN
k3      NaN  yellow    NaN  NaN
k4      NaN     NaN    NaN  red


<ipython-input-60-34da3d47952e>:7: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  print(df.pivot("keys","names","house"))
